name: test_workflow_reuse

on:
  workflow_call:

  push:
    branches:
      - feature-*CI* # for testing this script, all feature branches with "CI" in their name


jobs: 
  test_workflow_call:
    runs-on: ubuntu-latest
    env:
      SC_DEBUG: ../sc/build_debug
      P4EST_DEBUG: ../p4est/build_debug
    steps:
      - name: Test vars
        run: echo "[$SC_DEBUG] [$P4EST_DEBUG]"
    
